#!/bin/sh

# First, start system xinitrc's that may be added by packages:
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export PATH=$PATH:~/.local/bin

# Desktop background color.
xsetroot -solid "#333333"

# Set keyboard layout and options
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps ctrl:swap_lalt_lctl

# Natural scrolling direction for the touchpad.
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ASUF1208:00 2808:0218 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ASUF1208:00 2808:0218 Touchpad" "libinput Natural Scrolling Enabled" 1

# Start urxvtd
# urxvtd -q -f -o
# export TERMINAL=urxvtc

# And now I am moving over to kitty
# TODO: How to pre-start it?
export TERMINAL="`which kitty` -1"

export SHELL=/usr/bin/fish

xrdb -nocpp -merge ~/.Xresources

# export GDK_SCALE=2
# export QT_AUTO_SCREEN_SCALE_FACTOR=1

# Settings for the screen locker
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/Pictures/wallpapers/orig/ -type f"
export XSECURELOCK_IMAGE_DURATION_SECONDS=15
export XSECURELOCK_PASSWORD_PROMPT=disco
export XSECURELOCK_FONT="DejaVu Sans"

exec /usr/bin/i3
